/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Body
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class CreateNsRequest {
  @JsonProperty("nsdId")
  private String nsdId = null;

  @JsonProperty("nsName")
  private String nsName = null;

  @JsonProperty("nsDescription")
  private String nsDescription = null;

  public CreateNsRequest nsdId(String nsdId) {
    this.nsdId = nsdId;
    return this;
  }

   /**
   * An identifier with the intention of being globally unique. 
   * @return nsdId
  **/
  @Schema(required = true, description = "An identifier with the intention of being globally unique. ")
  public String getNsdId() {
    return nsdId;
  }

  public void setNsdId(String nsdId) {
    this.nsdId = nsdId;
  }

  public CreateNsRequest nsName(String nsName) {
    this.nsName = nsName;
    return this;
  }

   /**
   * Human-readable name of the NS instance to be created. 
   * @return nsName
  **/
  @Schema(required = true, description = "Human-readable name of the NS instance to be created. ")
  public String getNsName() {
    return nsName;
  }

  public void setNsName(String nsName) {
    this.nsName = nsName;
  }

  public CreateNsRequest nsDescription(String nsDescription) {
    this.nsDescription = nsDescription;
    return this;
  }

   /**
   * Human-readable description of the NS instance to be created. 
   * @return nsDescription
  **/
  @Schema(required = true, description = "Human-readable description of the NS instance to be created. ")
  public String getNsDescription() {
    return nsDescription;
  }

  public void setNsDescription(String nsDescription) {
    this.nsDescription = nsDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateNsRequest body = (CreateNsRequest) o;
    return Objects.equals(this.nsdId, body.nsdId) &&
        Objects.equals(this.nsName, body.nsName) &&
        Objects.equals(this.nsDescription, body.nsDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nsdId, nsName, nsDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("    nsdId: ").append(toIndentedString(nsdId)).append("\n");
    sb.append("    nsName: ").append(toIndentedString(nsName)).append("\n");
    sb.append("    nsDescription: ").append(toIndentedString(nsDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
