/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type represents an externally-managed internal VL. It shall comply with the provisions defined in Table 6.5.3.27-1. 
 */
@Schema(description = "This type represents an externally-managed internal VL. It shall comply with the provisions defined in Table 6.5.3.27-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdupdateExtManagedVirtualLinks {
  @JsonProperty("extManagedVirtualLinkId")
  private String extManagedVirtualLinkId = null;

  @JsonProperty("vnfVirtualLinkDescId")
  private String vnfVirtualLinkDescId = null;

  @JsonProperty("vimId")
  private String vimId = null;

  @JsonProperty("resourceProviderId")
  private String resourceProviderId = null;

  @JsonProperty("resourceId")
  private String resourceId = null;

  public NsInstancesnsInstanceIdupdateExtManagedVirtualLinks extManagedVirtualLinkId(String extManagedVirtualLinkId) {
    this.extManagedVirtualLinkId = extManagedVirtualLinkId;
    return this;
  }

   /**
   * An identifier with the intention of being globally unique. 
   * @return extManagedVirtualLinkId
  **/
  @Schema(description = "An identifier with the intention of being globally unique. ")
  public String getExtManagedVirtualLinkId() {
    return extManagedVirtualLinkId;
  }

  public void setExtManagedVirtualLinkId(String extManagedVirtualLinkId) {
    this.extManagedVirtualLinkId = extManagedVirtualLinkId;
  }

  public NsInstancesnsInstanceIdupdateExtManagedVirtualLinks vnfVirtualLinkDescId(String vnfVirtualLinkDescId) {
    this.vnfVirtualLinkDescId = vnfVirtualLinkDescId;
    return this;
  }

   /**
   * Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. 
   * @return vnfVirtualLinkDescId
  **/
  @Schema(required = true, description = "Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. ")
  public String getVnfVirtualLinkDescId() {
    return vnfVirtualLinkDescId;
  }

  public void setVnfVirtualLinkDescId(String vnfVirtualLinkDescId) {
    this.vnfVirtualLinkDescId = vnfVirtualLinkDescId;
  }

  public NsInstancesnsInstanceIdupdateExtManagedVirtualLinks vimId(String vimId) {
    this.vimId = vimId;
    return this;
  }

   /**
   * An identifier with the intention of being globally unique. 
   * @return vimId
  **/
  @Schema(description = "An identifier with the intention of being globally unique. ")
  public String getVimId() {
    return vimId;
  }

  public void setVimId(String vimId) {
    this.vimId = vimId;
  }

  public NsInstancesnsInstanceIdupdateExtManagedVirtualLinks resourceProviderId(String resourceProviderId) {
    this.resourceProviderId = resourceProviderId;
    return this;
  }

   /**
   * An identifier with the intention of being globally unique. 
   * @return resourceProviderId
  **/
  @Schema(description = "An identifier with the intention of being globally unique. ")
  public String getResourceProviderId() {
    return resourceProviderId;
  }

  public void setResourceProviderId(String resourceProviderId) {
    this.resourceProviderId = resourceProviderId;
  }

  public NsInstancesnsInstanceIdupdateExtManagedVirtualLinks resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * An identifier maintained by the VIM or other resource provider. It is expected to be unique within the VIM instance. Representation: string of variable length. 
   * @return resourceId
  **/
  @Schema(required = true, description = "An identifier maintained by the VIM or other resource provider. It is expected to be unique within the VIM instance. Representation: string of variable length. ")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdupdateExtManagedVirtualLinks nsInstancesnsInstanceIdupdateExtManagedVirtualLinks = (NsInstancesnsInstanceIdupdateExtManagedVirtualLinks) o;
    return Objects.equals(this.extManagedVirtualLinkId, nsInstancesnsInstanceIdupdateExtManagedVirtualLinks.extManagedVirtualLinkId) &&
        Objects.equals(this.vnfVirtualLinkDescId, nsInstancesnsInstanceIdupdateExtManagedVirtualLinks.vnfVirtualLinkDescId) &&
        Objects.equals(this.vimId, nsInstancesnsInstanceIdupdateExtManagedVirtualLinks.vimId) &&
        Objects.equals(this.resourceProviderId, nsInstancesnsInstanceIdupdateExtManagedVirtualLinks.resourceProviderId) &&
        Objects.equals(this.resourceId, nsInstancesnsInstanceIdupdateExtManagedVirtualLinks.resourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extManagedVirtualLinkId, vnfVirtualLinkDescId, vimId, resourceProviderId, resourceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdupdateExtManagedVirtualLinks {\n");
    
    sb.append("    extManagedVirtualLinkId: ").append(toIndentedString(extManagedVirtualLinkId)).append("\n");
    sb.append("    vnfVirtualLinkDescId: ").append(toIndentedString(vnfVirtualLinkDescId)).append("\n");
    sb.append("    vimId: ").append(toIndentedString(vimId)).append("\n");
    sb.append("    resourceProviderId: ").append(toIndentedString(resourceProviderId)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
