/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type specifies an existing NS instance for which the DF needs to be changed. This specifies the new DF, the instantiationLevel of the new DF that may be used and the additional parameters as input for the flavour change. It shall comply with the provisions defined in Table 6.5.3.39-1. 
 */
@Schema(description = "This type specifies an existing NS instance for which the DF needs to be changed. This specifies the new DF, the instantiationLevel of the new DF that may be used and the additional parameters as input for the flavour change. It shall comply with the provisions defined in Table 6.5.3.39-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdupdateChangeNsFlavourData {
  @JsonProperty("newNsFlavourId")
  private String newNsFlavourId = null;

  @JsonProperty("instantiationLevelId")
  private String instantiationLevelId = null;

  public NsInstancesnsInstanceIdupdateChangeNsFlavourData newNsFlavourId(String newNsFlavourId) {
    this.newNsFlavourId = newNsFlavourId;
    return this;
  }

   /**
   * An identifier that is unique within a NS descriptor. Representation: string of variable length. 
   * @return newNsFlavourId
  **/
  @Schema(required = true, description = "An identifier that is unique within a NS descriptor. Representation: string of variable length. ")
  public String getNewNsFlavourId() {
    return newNsFlavourId;
  }

  public void setNewNsFlavourId(String newNsFlavourId) {
    this.newNsFlavourId = newNsFlavourId;
  }

  public NsInstancesnsInstanceIdupdateChangeNsFlavourData instantiationLevelId(String instantiationLevelId) {
    this.instantiationLevelId = instantiationLevelId;
    return this;
  }

   /**
   * An identifier that is unique within a NS descriptor. Representation: string of variable length. 
   * @return instantiationLevelId
  **/
  @Schema(description = "An identifier that is unique within a NS descriptor. Representation: string of variable length. ")
  public String getInstantiationLevelId() {
    return instantiationLevelId;
  }

  public void setInstantiationLevelId(String instantiationLevelId) {
    this.instantiationLevelId = instantiationLevelId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdupdateChangeNsFlavourData nsInstancesnsInstanceIdupdateChangeNsFlavourData = (NsInstancesnsInstanceIdupdateChangeNsFlavourData) o;
    return Objects.equals(this.newNsFlavourId, nsInstancesnsInstanceIdupdateChangeNsFlavourData.newNsFlavourId) &&
        Objects.equals(this.instantiationLevelId, nsInstancesnsInstanceIdupdateChangeNsFlavourData.instantiationLevelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newNsFlavourId, instantiationLevelId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdupdateChangeNsFlavourData {\n");
    
    sb.append("    newNsFlavourId: ").append(toIndentedString(newNsFlavourId)).append("\n");
    sb.append("    instantiationLevelId: ").append(toIndentedString(instantiationLevelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
