/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type represents configuration information for external CPs created from a CPD. 
 */
@Schema(description = "This type represents configuration information for external CPs created from a CPD. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdupdateExtCps {
  @JsonProperty("cpdId")
  private String cpdId = null;

  @JsonProperty("cpConfig")
  private List<NsInstancesnsInstanceIdupdateCpConfig> cpConfig = null;

  public NsInstancesnsInstanceIdupdateExtCps cpdId(String cpdId) {
    this.cpdId = cpdId;
    return this;
  }

   /**
   * Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. 
   * @return cpdId
  **/
  @Schema(required = true, description = "Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. ")
  public String getCpdId() {
    return cpdId;
  }

  public void setCpdId(String cpdId) {
    this.cpdId = cpdId;
  }

  public NsInstancesnsInstanceIdupdateExtCps cpConfig(List<NsInstancesnsInstanceIdupdateCpConfig> cpConfig) {
    this.cpConfig = cpConfig;
    return this;
  }

  public NsInstancesnsInstanceIdupdateExtCps addCpConfigItem(NsInstancesnsInstanceIdupdateCpConfig cpConfigItem) {
    if (this.cpConfig == null) {
      this.cpConfig = new ArrayList<>();
    }
    this.cpConfig.add(cpConfigItem);
    return this;
  }

   /**
   * List of instance data that need to be configured on the CP instances created from the respective CPD. 
   * @return cpConfig
  **/
  @Schema(description = "List of instance data that need to be configured on the CP instances created from the respective CPD. ")
  public List<NsInstancesnsInstanceIdupdateCpConfig> getCpConfig() {
    return cpConfig;
  }

  public void setCpConfig(List<NsInstancesnsInstanceIdupdateCpConfig> cpConfig) {
    this.cpConfig = cpConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdupdateExtCps nsInstancesnsInstanceIdupdateExtCps = (NsInstancesnsInstanceIdupdateExtCps) o;
    return Objects.equals(this.cpdId, nsInstancesnsInstanceIdupdateExtCps.cpdId) &&
        Objects.equals(this.cpConfig, nsInstancesnsInstanceIdupdateExtCps.cpConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpdId, cpConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdupdateExtCps {\n");
    
    sb.append("    cpdId: ").append(toIndentedString(cpdId)).append("\n");
    sb.append("    cpConfig: ").append(toIndentedString(cpConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
