/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type represents the information used to scale an NS instance to a target size. The target size is either expressed as an NS instantiation level or as a list of NS scale levels, one per NS scaling aspect, of the current DF. The NS instantiation levels, the NS scaling aspects and their corresponding NS scale levels applicable to the NS instance are declared in the NSD. 
 */
@Schema(description = "This type represents the information used to scale an NS instance to a target size. The target size is either expressed as an NS instantiation level or as a list of NS scale levels, one per NS scaling aspect, of the current DF. The NS instantiation levels, the NS scaling aspects and their corresponding NS scale levels applicable to the NS instance are declared in the NSD. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData {
  @JsonProperty("nsInstantiationLevel")
  private String nsInstantiationLevel = null;

  @JsonProperty("nsScaleInfo")
  private List<NsInstancesNsInstanceNsScaleStatus> nsScaleInfo = null;

  public NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData nsInstantiationLevel(String nsInstantiationLevel) {
    this.nsInstantiationLevel = nsInstantiationLevel;
    return this;
  }

   /**
   * An identifier that is unique within a NS descriptor. Representation: string of variable length. 
   * @return nsInstantiationLevel
  **/
  @Schema(description = "An identifier that is unique within a NS descriptor. Representation: string of variable length. ")
  public String getNsInstantiationLevel() {
    return nsInstantiationLevel;
  }

  public void setNsInstantiationLevel(String nsInstantiationLevel) {
    this.nsInstantiationLevel = nsInstantiationLevel;
  }

  public NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData nsScaleInfo(List<NsInstancesNsInstanceNsScaleStatus> nsScaleInfo) {
    this.nsScaleInfo = nsScaleInfo;
    return this;
  }

  public NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData addNsScaleInfoItem(NsInstancesNsInstanceNsScaleStatus nsScaleInfoItem) {
    if (this.nsScaleInfo == null) {
      this.nsScaleInfo = new ArrayList<>();
    }
    this.nsScaleInfo.add(nsScaleInfoItem);
    return this;
  }

   /**
   * For each NS scaling aspect of the current DF, defines the target NS scale level to which the NS instance is to be scaled. 
   * @return nsScaleInfo
  **/
  @Schema(description = "For each NS scaling aspect of the current DF, defines the target NS scale level to which the NS instance is to be scaled. ")
  public List<NsInstancesNsInstanceNsScaleStatus> getNsScaleInfo() {
    return nsScaleInfo;
  }

  public void setNsScaleInfo(List<NsInstancesNsInstanceNsScaleStatus> nsScaleInfo) {
    this.nsScaleInfo = nsScaleInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData nsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData = (NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData) o;
    return Objects.equals(this.nsInstantiationLevel, nsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData.nsInstantiationLevel) &&
        Objects.equals(this.nsScaleInfo, nsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData.nsScaleInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nsInstantiationLevel, nsScaleInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdscaleScaleNsDataScaleNsToLevelData {\n");
    
    sb.append("    nsInstantiationLevel: ").append(toIndentedString(nsInstantiationLevel)).append("\n");
    sb.append("    nsScaleInfo: ").append(toIndentedString(nsScaleInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
