/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type specifies the parameters used for the creation of a new VNFFG instance. It shall comply with the provisions defined in Table 6.5.3.36-1. 
 */
@Schema(description = "This type specifies the parameters used for the creation of a new VNFFG instance. It shall comply with the provisions defined in Table 6.5.3.36-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdupdateAddVnffg {
  @JsonProperty("targetNsInstanceId")
  private String targetNsInstanceId = null;

  @JsonProperty("vnffgName")
  private String vnffgName = null;

  @JsonProperty("description")
  private String description = null;

  public NsInstancesnsInstanceIdupdateAddVnffg targetNsInstanceId(String targetNsInstanceId) {
    this.targetNsInstanceId = targetNsInstanceId;
    return this;
  }

   /**
   * An identifier that is unique within a NS descriptor. Representation: string of variable length. 
   * @return targetNsInstanceId
  **/
  @Schema(description = "An identifier that is unique within a NS descriptor. Representation: string of variable length. ")
  public String getTargetNsInstanceId() {
    return targetNsInstanceId;
  }

  public void setTargetNsInstanceId(String targetNsInstanceId) {
    this.targetNsInstanceId = targetNsInstanceId;
  }

  public NsInstancesnsInstanceIdupdateAddVnffg vnffgName(String vnffgName) {
    this.vnffgName = vnffgName;
    return this;
  }

   /**
   * Human readable name for the VNFFG. 
   * @return vnffgName
  **/
  @Schema(required = true, description = "Human readable name for the VNFFG. ")
  public String getVnffgName() {
    return vnffgName;
  }

  public void setVnffgName(String vnffgName) {
    this.vnffgName = vnffgName;
  }

  public NsInstancesnsInstanceIdupdateAddVnffg description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Human readable description for the VNFFG. 
   * @return description
  **/
  @Schema(required = true, description = "Human readable description for the VNFFG. ")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdupdateAddVnffg nsInstancesnsInstanceIdupdateAddVnffg = (NsInstancesnsInstanceIdupdateAddVnffg) o;
    return Objects.equals(this.targetNsInstanceId, nsInstancesnsInstanceIdupdateAddVnffg.targetNsInstanceId) &&
        Objects.equals(this.vnffgName, nsInstancesnsInstanceIdupdateAddVnffg.vnffgName) &&
        Objects.equals(this.description, nsInstancesnsInstanceIdupdateAddVnffg.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetNsInstanceId, vnffgName, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdupdateAddVnffg {\n");
    
    sb.append("    targetNsInstanceId: ").append(toIndentedString(targetNsInstanceId)).append("\n");
    sb.append("    vnffgName: ").append(toIndentedString(vnffgName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
