/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type specifies the parameters used for the update of an existing VNFFG instance. It shall comply with the provisions defined in Table 6.5.3.37-1. 
 */
@Schema(description = "This type specifies the parameters used for the update of an existing VNFFG instance. It shall comply with the provisions defined in Table 6.5.3.37-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdupdateUpdateVnffg {
  @JsonProperty("vnffgInfoId")
  private String vnffgInfoId = null;

  @JsonProperty("nfp")
  private List<NsInstancesnsInstanceIdupdateNfp> nfp = null;

  @JsonProperty("nfpInfoId")
  private List<String> nfpInfoId = null;

  public NsInstancesnsInstanceIdupdateUpdateVnffg vnffgInfoId(String vnffgInfoId) {
    this.vnffgInfoId = vnffgInfoId;
    return this;
  }

   /**
   * An identifier that is unique with respect to a NS. Representation: string of variable length. 
   * @return vnffgInfoId
  **/
  @Schema(required = true, description = "An identifier that is unique with respect to a NS. Representation: string of variable length. ")
  public String getVnffgInfoId() {
    return vnffgInfoId;
  }

  public void setVnffgInfoId(String vnffgInfoId) {
    this.vnffgInfoId = vnffgInfoId;
  }

  public NsInstancesnsInstanceIdupdateUpdateVnffg nfp(List<NsInstancesnsInstanceIdupdateNfp> nfp) {
    this.nfp = nfp;
    return this;
  }

  public NsInstancesnsInstanceIdupdateUpdateVnffg addNfpItem(NsInstancesnsInstanceIdupdateNfp nfpItem) {
    if (this.nfp == null) {
      this.nfp = new ArrayList<>();
    }
    this.nfp.add(nfpItem);
    return this;
  }

   /**
   * Indicate the desired new NFP(s) for a given VNFFG after the operations of addition/removal of NS components (e.g. VNFs, VLs, etc.) have been completed, or indicate the updated or newly created NFP classification and selection rule which applied to an existing NFP. 
   * @return nfp
  **/
  @Schema(description = "Indicate the desired new NFP(s) for a given VNFFG after the operations of addition/removal of NS components (e.g. VNFs, VLs, etc.) have been completed, or indicate the updated or newly created NFP classification and selection rule which applied to an existing NFP. ")
  public List<NsInstancesnsInstanceIdupdateNfp> getNfp() {
    return nfp;
  }

  public void setNfp(List<NsInstancesnsInstanceIdupdateNfp> nfp) {
    this.nfp = nfp;
  }

  public NsInstancesnsInstanceIdupdateUpdateVnffg nfpInfoId(List<String> nfpInfoId) {
    this.nfpInfoId = nfpInfoId;
    return this;
  }

  public NsInstancesnsInstanceIdupdateUpdateVnffg addNfpInfoIdItem(String nfpInfoIdItem) {
    if (this.nfpInfoId == null) {
      this.nfpInfoId = new ArrayList<>();
    }
    this.nfpInfoId.add(nfpInfoIdItem);
    return this;
  }

   /**
   * Identifier(s) of the NFP to be deleted from a given VNFFG. 
   * @return nfpInfoId
  **/
  @Schema(description = "Identifier(s) of the NFP to be deleted from a given VNFFG. ")
  public List<String> getNfpInfoId() {
    return nfpInfoId;
  }

  public void setNfpInfoId(List<String> nfpInfoId) {
    this.nfpInfoId = nfpInfoId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdupdateUpdateVnffg nsInstancesnsInstanceIdupdateUpdateVnffg = (NsInstancesnsInstanceIdupdateUpdateVnffg) o;
    return Objects.equals(this.vnffgInfoId, nsInstancesnsInstanceIdupdateUpdateVnffg.vnffgInfoId) &&
        Objects.equals(this.nfp, nsInstancesnsInstanceIdupdateUpdateVnffg.nfp) &&
        Objects.equals(this.nfpInfoId, nsInstancesnsInstanceIdupdateUpdateVnffg.nfpInfoId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vnffgInfoId, nfp, nfpInfoId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdupdateUpdateVnffg {\n");
    
    sb.append("    vnffgInfoId: ").append(toIndentedString(vnffgInfoId)).append("\n");
    sb.append("    nfp: ").append(toIndentedString(nfp)).append("\n");
    sb.append("    nfpInfoId: ").append(toIndentedString(nfpInfoId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
