/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type represents the information that allows addressing a virtualised resource that is used by an internal VL instance in a VNF instance. 
 */
@Schema(description = "This type represents the information that allows addressing a virtualised resource that is used by an internal VL instance in a VNF instance. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("vnfVirtualLinkDescId")
  private String vnfVirtualLinkDescId = null;

  @JsonProperty("networkResource")
  private NsInstancesNsInstanceInstantiatedVnfInfoResourceHandle networkResource = null;

  @JsonProperty("reservationId")
  private String reservationId = null;

  @JsonProperty("vnfLinkPorts")
  private List<NsInstancesNsInstanceInstantiatedVnfInfoVnfLinkPorts> vnfLinkPorts = null;

  @JsonProperty("metadata")
  private Object metadata = null;

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * An identifier that is unique for the respective type within a VNF instance, but may not be globally unique. 
   * @return id
  **/
  @Schema(required = true, description = "An identifier that is unique for the respective type within a VNF instance, but may not be globally unique. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo vnfVirtualLinkDescId(String vnfVirtualLinkDescId) {
    this.vnfVirtualLinkDescId = vnfVirtualLinkDescId;
    return this;
  }

   /**
   * Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. 
   * @return vnfVirtualLinkDescId
  **/
  @Schema(required = true, description = "Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. ")
  public String getVnfVirtualLinkDescId() {
    return vnfVirtualLinkDescId;
  }

  public void setVnfVirtualLinkDescId(String vnfVirtualLinkDescId) {
    this.vnfVirtualLinkDescId = vnfVirtualLinkDescId;
  }

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo networkResource(NsInstancesNsInstanceInstantiatedVnfInfoResourceHandle networkResource) {
    this.networkResource = networkResource;
    return this;
  }

   /**
   * Get networkResource
   * @return networkResource
  **/
  @Schema(required = true, description = "")
  public NsInstancesNsInstanceInstantiatedVnfInfoResourceHandle getNetworkResource() {
    return networkResource;
  }

  public void setNetworkResource(NsInstancesNsInstanceInstantiatedVnfInfoResourceHandle networkResource) {
    this.networkResource = networkResource;
  }

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo reservationId(String reservationId) {
    this.reservationId = reservationId;
    return this;
  }

   /**
   * An identifier with the intention of being globally unique. 
   * @return reservationId
  **/
  @Schema(description = "An identifier with the intention of being globally unique. ")
  public String getReservationId() {
    return reservationId;
  }

  public void setReservationId(String reservationId) {
    this.reservationId = reservationId;
  }

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo vnfLinkPorts(List<NsInstancesNsInstanceInstantiatedVnfInfoVnfLinkPorts> vnfLinkPorts) {
    this.vnfLinkPorts = vnfLinkPorts;
    return this;
  }

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo addVnfLinkPortsItem(NsInstancesNsInstanceInstantiatedVnfInfoVnfLinkPorts vnfLinkPortsItem) {
    if (this.vnfLinkPorts == null) {
      this.vnfLinkPorts = new ArrayList<>();
    }
    this.vnfLinkPorts.add(vnfLinkPortsItem);
    return this;
  }

   /**
   * Links ports of this VL. Shall be present when the linkPort is used for external connectivity by the VNF (refer to VnfLinkPortInfo). May be present otherwise. 
   * @return vnfLinkPorts
  **/
  @Schema(description = "Links ports of this VL. Shall be present when the linkPort is used for external connectivity by the VNF (refer to VnfLinkPortInfo). May be present otherwise. ")
  public List<NsInstancesNsInstanceInstantiatedVnfInfoVnfLinkPorts> getVnfLinkPorts() {
    return vnfLinkPorts;
  }

  public void setVnfLinkPorts(List<NsInstancesNsInstanceInstantiatedVnfInfoVnfLinkPorts> vnfLinkPorts) {
    this.vnfLinkPorts = vnfLinkPorts;
  }

  public NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. 
   * @return metadata
  **/
  @Schema(description = "This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. ")
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo = (NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo) o;
    return Objects.equals(this.id, nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo.id) &&
        Objects.equals(this.vnfVirtualLinkDescId, nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo.vnfVirtualLinkDescId) &&
        Objects.equals(this.networkResource, nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo.networkResource) &&
        Objects.equals(this.reservationId, nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo.reservationId) &&
        Objects.equals(this.vnfLinkPorts, nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo.vnfLinkPorts) &&
        Objects.equals(this.metadata, nsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, vnfVirtualLinkDescId, networkResource, reservationId, vnfLinkPorts, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesNsInstanceInstantiatedVnfInfoVirtualLinkResourceInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    vnfVirtualLinkDescId: ").append(toIndentedString(vnfVirtualLinkDescId)).append("\n");
    sb.append("    networkResource: ").append(toIndentedString(networkResource)).append("\n");
    sb.append("    reservationId: ").append(toIndentedString(reservationId)).append("\n");
    sb.append("    vnfLinkPorts: ").append(toIndentedString(vnfLinkPorts)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
