/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.3.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.openslice.sol005nbi.model.nslcm;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * This type represents the information related to a SAP of a NS. The InstantiateVnfData data type specifies the parameters that are needed for VNF instantiation. This information element is used for the bottom-up NS creation when the OSS/BSS explicitly requests VNF instantiation for a given NS. When the NFVO invokes the Instantiate VNF update operation, a set of these parameters are then passed by the NFVO to the VNFM. It shall comply with the provisions defined in Table 6.5.3.24-1. 
 */
@Schema(description = "This type represents the information related to a SAP of a NS. The InstantiateVnfData data type specifies the parameters that are needed for VNF instantiation. This information element is used for the bottom-up NS creation when the OSS/BSS explicitly requests VNF instantiation for a given NS. When the NFVO invokes the Instantiate VNF update operation, a set of these parameters are then passed by the NFVO to the VNFM. It shall comply with the provisions defined in Table 6.5.3.24-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-28T00:48:29.393+02:00[Europe/Athens]")
public class NsInstancesnsInstanceIdupdateInstantiateVnfData {
  @JsonProperty("vnfdId")
  private String vnfdId = null;

  @JsonProperty("vnfFlavourId")
  private String vnfFlavourId = null;

  @JsonProperty("vnfInstantiationLevelId")
  private String vnfInstantiationLevelId = null;

  @JsonProperty("vnfInstanceName")
  private String vnfInstanceName = null;

  @JsonProperty("vnfInstanceDescription")
  private String vnfInstanceDescription = null;

  @JsonProperty("extVirtualLinks")
  private List<NsInstancesnsInstanceIdupdateExtVirtualLinks> extVirtualLinks = null;

  @JsonProperty("extManagedVirtualLinks")
  private List<NsInstancesnsInstanceIdupdateExtManagedVirtualLinks> extManagedVirtualLinks = null;

  @JsonProperty("localizationLanguage")
  private String localizationLanguage = null;

  @JsonProperty("vnfConfigurableProperties")
  private Object vnfConfigurableProperties = null;

  @JsonProperty("additionalParams")
  private Object additionalParams = null;

  @JsonProperty("metadata")
  private Object metadata = null;

  @JsonProperty("extensions")
  private Object extensions = null;

  @JsonProperty("locationConstraints")
  private NsInstancesnsInstanceIdinstantiateLocationConstraints1 locationConstraints = null;

  public NsInstancesnsInstanceIdupdateInstantiateVnfData vnfdId(String vnfdId) {
    this.vnfdId = vnfdId;
    return this;
  }

   /**
   * An identifier with the intention of being globally unique. 
   * @return vnfdId
  **/
  @Schema(required = true, description = "An identifier with the intention of being globally unique. ")
  public String getVnfdId() {
    return vnfdId;
  }

  public void setVnfdId(String vnfdId) {
    this.vnfdId = vnfdId;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData vnfFlavourId(String vnfFlavourId) {
    this.vnfFlavourId = vnfFlavourId;
    return this;
  }

   /**
   * Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. 
   * @return vnfFlavourId
  **/
  @Schema(required = true, description = "Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. ")
  public String getVnfFlavourId() {
    return vnfFlavourId;
  }

  public void setVnfFlavourId(String vnfFlavourId) {
    this.vnfFlavourId = vnfFlavourId;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData vnfInstantiationLevelId(String vnfInstantiationLevelId) {
    this.vnfInstantiationLevelId = vnfInstantiationLevelId;
    return this;
  }

   /**
   * Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. 
   * @return vnfInstantiationLevelId
  **/
  @Schema(description = "Identifier of the VNF Virtual Link Descriptor (VLD) in the VNFD. ")
  public String getVnfInstantiationLevelId() {
    return vnfInstantiationLevelId;
  }

  public void setVnfInstantiationLevelId(String vnfInstantiationLevelId) {
    this.vnfInstantiationLevelId = vnfInstantiationLevelId;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData vnfInstanceName(String vnfInstanceName) {
    this.vnfInstanceName = vnfInstanceName;
    return this;
  }

   /**
   * Human-readable name of the VNF instance to be created. 
   * @return vnfInstanceName
  **/
  @Schema(description = "Human-readable name of the VNF instance to be created. ")
  public String getVnfInstanceName() {
    return vnfInstanceName;
  }

  public void setVnfInstanceName(String vnfInstanceName) {
    this.vnfInstanceName = vnfInstanceName;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData vnfInstanceDescription(String vnfInstanceDescription) {
    this.vnfInstanceDescription = vnfInstanceDescription;
    return this;
  }

   /**
   * Human-readable description of the VNF instance to be created. 
   * @return vnfInstanceDescription
  **/
  @Schema(description = "Human-readable description of the VNF instance to be created. ")
  public String getVnfInstanceDescription() {
    return vnfInstanceDescription;
  }

  public void setVnfInstanceDescription(String vnfInstanceDescription) {
    this.vnfInstanceDescription = vnfInstanceDescription;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData extVirtualLinks(List<NsInstancesnsInstanceIdupdateExtVirtualLinks> extVirtualLinks) {
    this.extVirtualLinks = extVirtualLinks;
    return this;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData addExtVirtualLinksItem(NsInstancesnsInstanceIdupdateExtVirtualLinks extVirtualLinksItem) {
    if (this.extVirtualLinks == null) {
      this.extVirtualLinks = new ArrayList<>();
    }
    this.extVirtualLinks.add(extVirtualLinksItem);
    return this;
  }

   /**
   * Information about external VLs to connect the VNF to. 
   * @return extVirtualLinks
  **/
  @Schema(description = "Information about external VLs to connect the VNF to. ")
  public List<NsInstancesnsInstanceIdupdateExtVirtualLinks> getExtVirtualLinks() {
    return extVirtualLinks;
  }

  public void setExtVirtualLinks(List<NsInstancesnsInstanceIdupdateExtVirtualLinks> extVirtualLinks) {
    this.extVirtualLinks = extVirtualLinks;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData extManagedVirtualLinks(List<NsInstancesnsInstanceIdupdateExtManagedVirtualLinks> extManagedVirtualLinks) {
    this.extManagedVirtualLinks = extManagedVirtualLinks;
    return this;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData addExtManagedVirtualLinksItem(NsInstancesnsInstanceIdupdateExtManagedVirtualLinks extManagedVirtualLinksItem) {
    if (this.extManagedVirtualLinks == null) {
      this.extManagedVirtualLinks = new ArrayList<>();
    }
    this.extManagedVirtualLinks.add(extManagedVirtualLinksItem);
    return this;
  }

   /**
   * Information about internal VLs that are managed by other entities than the VNFM. 
   * @return extManagedVirtualLinks
  **/
  @Schema(description = "Information about internal VLs that are managed by other entities than the VNFM. ")
  public List<NsInstancesnsInstanceIdupdateExtManagedVirtualLinks> getExtManagedVirtualLinks() {
    return extManagedVirtualLinks;
  }

  public void setExtManagedVirtualLinks(List<NsInstancesnsInstanceIdupdateExtManagedVirtualLinks> extManagedVirtualLinks) {
    this.extManagedVirtualLinks = extManagedVirtualLinks;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData localizationLanguage(String localizationLanguage) {
    this.localizationLanguage = localizationLanguage;
    return this;
  }

   /**
   * Localization language of the VNF to be instantiated. The value shall comply with the format defined in IETF RFC 5646. 
   * @return localizationLanguage
  **/
  @Schema(description = "Localization language of the VNF to be instantiated. The value shall comply with the format defined in IETF RFC 5646. ")
  public String getLocalizationLanguage() {
    return localizationLanguage;
  }

  public void setLocalizationLanguage(String localizationLanguage) {
    this.localizationLanguage = localizationLanguage;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData vnfConfigurableProperties(Object vnfConfigurableProperties) {
    this.vnfConfigurableProperties = vnfConfigurableProperties;
    return this;
  }

   /**
   * This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. 
   * @return vnfConfigurableProperties
  **/
  @Schema(description = "This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. ")
  public Object getVnfConfigurableProperties() {
    return vnfConfigurableProperties;
  }

  public void setVnfConfigurableProperties(Object vnfConfigurableProperties) {
    this.vnfConfigurableProperties = vnfConfigurableProperties;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData additionalParams(Object additionalParams) {
    this.additionalParams = additionalParams;
    return this;
  }

   /**
   * This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. 
   * @return additionalParams
  **/
  @Schema(description = "This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. ")
  public Object getAdditionalParams() {
    return additionalParams;
  }

  public void setAdditionalParams(Object additionalParams) {
    this.additionalParams = additionalParams;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. 
   * @return metadata
  **/
  @Schema(description = "This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. ")
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData extensions(Object extensions) {
    this.extensions = extensions;
    return this;
  }

   /**
   * This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. 
   * @return extensions
  **/
  @Schema(description = "This type represents a list of key-value pairs. The order of the pairs in the list is not significant. In JSON, a set of key- value pairs is represented as an object. It shall comply with the provisions defined in clause 4 of IETF RFC 7159. ")
  public Object getExtensions() {
    return extensions;
  }

  public void setExtensions(Object extensions) {
    this.extensions = extensions;
  }

  public NsInstancesnsInstanceIdupdateInstantiateVnfData locationConstraints(NsInstancesnsInstanceIdinstantiateLocationConstraints1 locationConstraints) {
    this.locationConstraints = locationConstraints;
    return this;
  }

   /**
   * Get locationConstraints
   * @return locationConstraints
  **/
  @Schema(description = "")
  public NsInstancesnsInstanceIdinstantiateLocationConstraints1 getLocationConstraints() {
    return locationConstraints;
  }

  public void setLocationConstraints(NsInstancesnsInstanceIdinstantiateLocationConstraints1 locationConstraints) {
    this.locationConstraints = locationConstraints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsInstancesnsInstanceIdupdateInstantiateVnfData nsInstancesnsInstanceIdupdateInstantiateVnfData = (NsInstancesnsInstanceIdupdateInstantiateVnfData) o;
    return Objects.equals(this.vnfdId, nsInstancesnsInstanceIdupdateInstantiateVnfData.vnfdId) &&
        Objects.equals(this.vnfFlavourId, nsInstancesnsInstanceIdupdateInstantiateVnfData.vnfFlavourId) &&
        Objects.equals(this.vnfInstantiationLevelId, nsInstancesnsInstanceIdupdateInstantiateVnfData.vnfInstantiationLevelId) &&
        Objects.equals(this.vnfInstanceName, nsInstancesnsInstanceIdupdateInstantiateVnfData.vnfInstanceName) &&
        Objects.equals(this.vnfInstanceDescription, nsInstancesnsInstanceIdupdateInstantiateVnfData.vnfInstanceDescription) &&
        Objects.equals(this.extVirtualLinks, nsInstancesnsInstanceIdupdateInstantiateVnfData.extVirtualLinks) &&
        Objects.equals(this.extManagedVirtualLinks, nsInstancesnsInstanceIdupdateInstantiateVnfData.extManagedVirtualLinks) &&
        Objects.equals(this.localizationLanguage, nsInstancesnsInstanceIdupdateInstantiateVnfData.localizationLanguage) &&
        Objects.equals(this.vnfConfigurableProperties, nsInstancesnsInstanceIdupdateInstantiateVnfData.vnfConfigurableProperties) &&
        Objects.equals(this.additionalParams, nsInstancesnsInstanceIdupdateInstantiateVnfData.additionalParams) &&
        Objects.equals(this.metadata, nsInstancesnsInstanceIdupdateInstantiateVnfData.metadata) &&
        Objects.equals(this.extensions, nsInstancesnsInstanceIdupdateInstantiateVnfData.extensions) &&
        Objects.equals(this.locationConstraints, nsInstancesnsInstanceIdupdateInstantiateVnfData.locationConstraints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vnfdId, vnfFlavourId, vnfInstantiationLevelId, vnfInstanceName, vnfInstanceDescription, extVirtualLinks, extManagedVirtualLinks, localizationLanguage, vnfConfigurableProperties, additionalParams, metadata, extensions, locationConstraints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsInstancesnsInstanceIdupdateInstantiateVnfData {\n");
    
    sb.append("    vnfdId: ").append(toIndentedString(vnfdId)).append("\n");
    sb.append("    vnfFlavourId: ").append(toIndentedString(vnfFlavourId)).append("\n");
    sb.append("    vnfInstantiationLevelId: ").append(toIndentedString(vnfInstantiationLevelId)).append("\n");
    sb.append("    vnfInstanceName: ").append(toIndentedString(vnfInstanceName)).append("\n");
    sb.append("    vnfInstanceDescription: ").append(toIndentedString(vnfInstanceDescription)).append("\n");
    sb.append("    extVirtualLinks: ").append(toIndentedString(extVirtualLinks)).append("\n");
    sb.append("    extManagedVirtualLinks: ").append(toIndentedString(extManagedVirtualLinks)).append("\n");
    sb.append("    localizationLanguage: ").append(toIndentedString(localizationLanguage)).append("\n");
    sb.append("    vnfConfigurableProperties: ").append(toIndentedString(vnfConfigurableProperties)).append("\n");
    sb.append("    additionalParams: ").append(toIndentedString(additionalParams)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("    locationConstraints: ").append(toIndentedString(locationConstraints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
